#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : R-SparseM
Version  : 1.84
Release  : 99
URL      : https://cran.r-project.org/src/contrib/SparseM_1.84.tar.gz
Source0  : https://cran.r-project.org/src/contrib/SparseM_1.84.tar.gz
Summary  : Sparse Linear Algebra
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-SparseM-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Versions of SparseM prior to 0.95 included a LICENSE file that described
some uncertainties over the licensing status of the fortran
code in src/cholesky.f.  As of 9 March 2012, original authors of cholesky.f,
Esmond Ng and Barry Peyton,  have now, very kindly,  given permission to
use cholesky.f under an open source license.  They have requested that
their code be credited via the following two publications:

%package lib
Summary: lib components for the R-SparseM package.
Group: Libraries

%description lib
lib components for the R-SparseM package.


%prep
%setup -q -n SparseM
pushd ..
cp -a SparseM buildavx2
popd
pushd ..
cp -a SparseM buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719332210

%install
export SOURCE_DATE_EPOCH=1719332210
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/SparseM/ChangeLog
/usr/lib64/R/library/SparseM/DESCRIPTION
/usr/lib64/R/library/SparseM/INDEX
/usr/lib64/R/library/SparseM/Meta/Rd.rds
/usr/lib64/R/library/SparseM/Meta/data.rds
/usr/lib64/R/library/SparseM/Meta/demo.rds
/usr/lib64/R/library/SparseM/Meta/features.rds
/usr/lib64/R/library/SparseM/Meta/hsearch.rds
/usr/lib64/R/library/SparseM/Meta/links.rds
/usr/lib64/R/library/SparseM/Meta/nsInfo.rds
/usr/lib64/R/library/SparseM/Meta/package.rds
/usr/lib64/R/library/SparseM/Meta/vignette.rds
/usr/lib64/R/library/SparseM/NAMESPACE
/usr/lib64/R/library/SparseM/R/SparseM
/usr/lib64/R/library/SparseM/R/SparseM.rdb
/usr/lib64/R/library/SparseM/R/SparseM.rdx
/usr/lib64/R/library/SparseM/TODO
/usr/lib64/R/library/SparseM/data/lsq.rda
/usr/lib64/R/library/SparseM/data/triogramX.rda
/usr/lib64/R/library/SparseM/demo/Binding.R
/usr/lib64/R/library/SparseM/demo/Coercion.R
/usr/lib64/R/library/SparseM/demo/LeastSquares.R
/usr/lib64/R/library/SparseM/demo/LinearAlgebra.R
/usr/lib64/R/library/SparseM/demo/Solve.R
/usr/lib64/R/library/SparseM/demo/Visualization.R
/usr/lib64/R/library/SparseM/doc/SparseM.R
/usr/lib64/R/library/SparseM/doc/SparseM.Rnw
/usr/lib64/R/library/SparseM/doc/SparseM.pdf
/usr/lib64/R/library/SparseM/doc/index.html
/usr/lib64/R/library/SparseM/extdata/lsq.out
/usr/lib64/R/library/SparseM/extdata/lsq.rra
/usr/lib64/R/library/SparseM/extdata/rua_32_ax.rua
/usr/lib64/R/library/SparseM/help/AnIndex
/usr/lib64/R/library/SparseM/help/SparseM.rdb
/usr/lib64/R/library/SparseM/help/SparseM.rdx
/usr/lib64/R/library/SparseM/help/aliases.rds
/usr/lib64/R/library/SparseM/help/paths.rds
/usr/lib64/R/library/SparseM/html/00Index.html
/usr/lib64/R/library/SparseM/html/R.css

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/SparseM/libs/SparseM.so
/V4/usr/lib64/R/library/SparseM/libs/SparseM.so
/usr/lib64/R/library/SparseM/libs/SparseM.so
